# Generated by Django 4.2.24 on 2025-09-24 17:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the AI agent', max_length=100)),
                ('agent_type', models.CharField(choices=[('message_redrafter', 'Message Redrafter'), ('reply_analyzer', 'Reply Analyzer'), ('chatbot', 'Chatbot'), ('content_generator', 'Content Generator'), ('sentiment_analyzer', 'Sentiment Analyzer')], help_text='Type of AI agent', max_length=20)),
                ('description', models.TextField(blank=True, help_text="Description of the agent's purpose")),
                ('model_name', models.CharField(default='gpt-3.5-turbo', help_text='AI model to use (e.g., gpt-3.5-turbo, gpt-4)', max_length=100)),
                ('temperature', models.FloatField(default=0.7, help_text='Creativity level (0.0 = deterministic, 2.0 = very creative)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_tokens', models.IntegerField(default=1000, help_text='Maximum tokens in response', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4000)])),
                ('system_prompt', models.TextField(help_text="System prompt that defines the agent's behavior and personality")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this agent is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Agent',
                'verbose_name_plural': 'AI Agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISentimentAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_content', models.TextField(help_text='Original message content')),
                ('message_id', models.CharField(blank=True, help_text='ID of the related message (if applicable)', max_length=100)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], help_text='Overall sentiment', max_length=20)),
                ('confidence_score', models.FloatField(help_text='Confidence score of the analysis (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('positive_score', models.FloatField(default=0.0, help_text='Positive sentiment score')),
                ('negative_score', models.FloatField(default=0.0, help_text='Negative sentiment score')),
                ('neutral_score', models.FloatField(default=0.0, help_text='Neutral sentiment score')),
                ('keywords', models.JSONField(default=list, help_text='Key words/phrases identified')),
                ('entities', models.JSONField(default=list, help_text='Named entities identified')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentiment_analyses', to='ai_agent.aiagent')),
            ],
            options={
                'verbose_name': 'AI Sentiment Analysis',
                'verbose_name_plural': 'AI Sentiment Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='AIProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('message_redraft', 'Message Redraft'), ('reply_analysis', 'Reply Analysis'), ('chatbot_response', 'Chatbot Response'), ('content_generation', 'Content Generation'), ('sentiment_analysis', 'Sentiment Analysis'), ('template_enhancement', 'Template Enhancement')], help_text='Type of AI operation performed', max_length=50)),
                ('input_data', models.JSONField(help_text='Input data for the AI operation')),
                ('output_data', models.JSONField(blank=True, help_text='Output data from the AI operation', null=True)),
                ('processing_time', models.FloatField(help_text='Time taken to process (in seconds)')),
                ('tokens_used', models.IntegerField(blank=True, help_text='Number of tokens used', null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=6, help_text='Estimated cost of the operation', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout'), ('rate_limited', 'Rate Limited')], default='success', help_text='Status of the AI operation', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if operation failed')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='ai_agent.aiagent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_processing_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Processing Log',
                'verbose_name_plural': 'AI Processing Logs',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name', max_length=100)),
                ('template_type', models.CharField(choices=[('greeting', 'Greeting'), ('follow_up', 'Follow Up'), ('complaint_response', 'Complaint Response'), ('confirmation', 'Confirmation'), ('promotion', 'Promotion'), ('custom', 'Custom')], help_text='Type of message template', max_length=50)),
                ('content', models.TextField(help_text='Template content with placeholders')),
                ('placeholders', models.JSONField(default=list, help_text="List of placeholder variables (e.g., ['customer_name', 'product_name'])")),
                ('use_ai_enhancement', models.BooleanField(default=False, help_text='Whether to use AI to enhance this template')),
                ('enhancement_prompt', models.TextField(blank=True, help_text='Prompt for AI to enhance the template')),
                ('usage_count', models.IntegerField(default=0, help_text='How many times this template has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Message Template',
                'verbose_name_plural': 'AI Message Templates',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIContentGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('message', 'Message'), ('email', 'Email'), ('social_post', 'Social Media Post'), ('ad_copy', 'Advertisement Copy'), ('blog_post', 'Blog Post'), ('description', 'Product/Service Description')], help_text='Type of content generated', max_length=50)),
                ('prompt', models.TextField(help_text='Prompt used to generate content')),
                ('generated_content', models.TextField(help_text='AI-generated content')),
                ('quality_score', models.FloatField(blank=True, help_text='Quality score of generated content (0.0 to 1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_used', models.BooleanField(default=False, help_text='Whether this content was used')),
                ('usage_count', models.IntegerField(default=0, help_text='How many times this content was used')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_content', to='ai_agent.aiagent')),
                ('related_message_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_content', to='ai_agent.aimessagetemplate')),
            ],
            options={
                'verbose_name': 'AI Content Generation',
                'verbose_name_plural': 'AI Content Generations',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=100)),
                ('context_data', models.JSONField(default=dict, help_text='Additional context data for the conversation')),
                ('messages', models.JSONField(default=list, help_text='List of messages in the conversation')),
                ('message_count', models.IntegerField(default=0, help_text='Number of messages in conversation')),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='ai_agent.aiagent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
                'ordering': ['-last_message_at'],
                'unique_together': {('agent', 'session_id')},
            },
        ),
    ]
