# Generated by Django 4.2.24 on 2025-09-24 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_agents', to=settings.AUTH_USER_MODEL),
        ),
    ]
