# Generated by Django 4.2.24 on 2025-09-26 20:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_agent', '0003_alter_aiconversation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprocessinglog',
            name='operation_type',
            field=models.CharField(choices=[('message_redraft', 'Message Redraft'), ('reply_analysis', 'Reply Analysis'), ('chatbot_response', 'Chatbot Response'), ('content_generation', 'Content Generation'), ('sentiment_analysis', 'Sentiment Analysis'), ('template_enhancement', 'Template Enhancement'), ('rag_query', 'RAG Query')], help_text='Type of AI operation performed', max_length=50),
        ),
        migrations.CreateModel(
            name='VectorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='The text content of the document')),
                ('title', models.CharField(help_text='Title or identifier for the document', max_length=500)),
                ('source_type', models.CharField(choices=[('trip', 'Trip'), ('itinerary', 'Itinerary'), ('faq', 'FAQ'), ('policy', 'Policy'), ('blog', 'Blog Post'), ('custom', 'Custom Content')], help_text='Type of source content', max_length=50)),
                ('source_id', models.CharField(help_text='ID of the source object (e.g., trip ID)', max_length=100)),
                ('source_url', models.URLField(blank=True, help_text='URL to the source content')),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding for similarity search', null=True)),
                ('embedding_model', models.CharField(default='text-embedding-ada-002', help_text='Model used to generate the embedding', max_length=100)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata for the document')),
                ('chunk_index', models.IntegerField(default=0, help_text='Index of this chunk within the source document')),
                ('total_chunks', models.IntegerField(default=1, help_text='Total number of chunks for this source document')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this document is active for search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vector Document',
                'verbose_name_plural': 'Vector Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='ai_agent_ve_source__25929b_idx'), models.Index(fields=['is_active', 'source_type'], name='ai_agent_ve_is_acti_e4f470_idx')],
            },
        ),
        migrations.CreateModel(
            name='RAGQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(help_text="The user's query")),
                ('rewritten_query', models.TextField(blank=True, help_text='AI-rewritten version of the query for better search')),
                ('retrieved_documents', models.JSONField(default=list, help_text='List of retrieved document IDs with similarity scores')),
                ('context_used', models.TextField(blank=True, help_text='Context provided to the LLM')),
                ('response', models.TextField(help_text='AI-generated response')),
                ('response_quality', models.FloatField(blank=True, help_text='Quality score of the response (0.0 to 1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('search_time', models.FloatField(help_text='Time taken for vector search (seconds)')),
                ('generation_time', models.FloatField(help_text='Time taken for response generation (seconds)')),
                ('total_time', models.FloatField(help_text='Total processing time (seconds)')),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], help_text='User rating of the response', null=True)),
                ('user_feedback', models.TextField(blank=True, help_text='User feedback on the response')),
                ('session_id', models.CharField(help_text='Session identifier', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RAG Query',
                'verbose_name_plural': 'RAG Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
