# Generated by Django 4.2.24 on 2025-09-26 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
                ('overview', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(default=list)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('duration', models.IntegerField()),
                ('tags', models.JSONField(default=list)),
                ('category', models.CharField(choices=[('cultural', 'Cultural'), ('adventure', 'Adventure'), ('spiritual', 'Spiritual'), ('beach', 'Beach'), ('trekking', 'Trekking'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('featured_status', models.CharField(choices=[('featured', 'Featured'), ('popular', 'Popular'), ('both', 'Both'), ('none', 'None')], default='none', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('inclusions', models.JSONField(default=list)),
                ('exclusions', models.JSONField(default=list)),
                ('things_to_carry', models.JSONField(default=list)),
                ('important_points', models.JSONField(default=list)),
                ('who_can_attend', models.JSONField(default=list)),
                ('itinerary', models.JSONField(default=list)),
                ('contact_info', models.JSONField(default=dict)),
                ('bank_details', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('vehicle_type', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('filling_fast', 'Filling Fast'), ('sold_out', 'Sold Out')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_slots', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='SeatMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle', models.CharField(max_length=100)),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
                ('seats', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_map', to='trips.tripslot')),
            ],
        ),
    ]
