# Generated by Django 4.2.24 on 2025-09-25 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('travelers', models.PositiveIntegerField(default=1)),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('experience_level', models.CharField(blank=True, max_length=50, null=True)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('source', models.CharField(default='home_page_modal', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='leads_lead_email_f663dc_idx'), models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'), models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx'), models.Index(fields=['destination'], name='leads_lead_destina_79403c_idx')],
            },
        ),
    ]
