# Generated by Django 4.2.24 on 2025-09-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecampaign',
            name='campaign_type',
            field=models.CharField(choices=[('standard', 'Standard Campaign'), ('personalized', 'AI Personalized'), ('automated', 'Automated Responses')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='personalization_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Rules for AI personalization'),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='column_mapping',
            field=models.JSONField(blank=True, help_text='Mapping of Excel columns to fields', null=True),
        ),
    ]
