# Generated by Django 4.2.24 on 2025-09-24 18:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messagecampaign_campaign_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for unsubscribing')),
                ('unsubscribed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, help_text='How they unsubscribed (e.g., reply, web)', max_length=50)),
            ],
            options={
                'ordering': ['-unsubscribed_at'],
            },
        ),
    ]
